### ISSUE TITLE
Simplify returning of views (Core)

### ISSUE THREAD

**Issue by dylanvdmerwe** [ASP-NET-Core-Boilerplate/Templates#152]
I understand that you are trying to be extremely explicit. But I am a complete believer in the least amount of code (simpler) wins. 

As such, in Asp.Net Core, an example of how your routing can be simplified:
```c#
       [HttpGet("", Name = HomeControllerRoute.GetIndex)]
        public IActionResult Index()
        {
            return this.View(HomeControllerAction.Index);
        }

        [HttpGet("about", Name = HomeControllerRoute.GetAbout)]
        public IActionResult About()
        {
            return this.View(HomeControllerAction.About);
        }

        [HttpGet("contact", Name = HomeControllerRoute.GetContact)]
        public IActionResult Contact()
        {
            return this.View(HomeControllerAction.Contact);
        }
```

To something like this:
```c#
        [HttpGet]
        public IActionResult Index()
        {
            return this.View();
        }

        [HttpGet(nameof(About))]
        public IActionResult About()
        {
            return this.View();
        }

        [HttpGet(nameof(Contact))]
        public IActionResult Contact()
        {
            return this.View();
        }
```

It does exactly the same thing, without being overly verbose.

**Comment by RehanSaeed** [comment]
I guess this is about taste and I should conform. Would you be willing to submit a PR for this?

**Comment by RehanSaeed** [comment]
I've archived the MVC boilerplate project due to the size and complexity of moving it to ASP.NET Core 2.0 with the latest and greatest web front end stuff like Bootstrap 4, Webpack, Workbox etc. I also had to learn all that stuff so needed time for that. I'm focusing my efforts on the API Boilerplate project and will bring back the MVC project better than ever before once I have the courage to attempt it.
