### ISSUE TITLE
Missing .sass-lint.yml file

### ISSUE THREAD

**Issue by dylanvdmerwe** [ASP-NET-Core-Boilerplate/Templates#154]
A rules/config file for the sass linter should be provided. 

See [here](https://raw.githubusercontent.com/sasstools/gulp-sass-lint/master/tests/.sass-lint.yml).

**Comment by RehanSaeed** [comment]
Will look at this once I have some time. Probably after VS 2017 upgrade.

**Comment by RehanSaeed** [comment]
I've archived the MVC boilerplate project due to the size and complexity of moving it to ASP.NET Core 2.0 with the latest and greatest web front end stuff like Bootstrap 4, Webpack, Workbox etc. I also had to learn all that stuff so needed time for that. I'm focusing my efforts on the API Boilerplate project and will bring back the MVC project better than ever before once I have the courage to attempt it.
